[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
scroll = "https://rpc.scroll.io"
scroll_sepolia = "https://sepolia-rpc.scroll.io"

[etherscan]
scroll = { key = "${SCROLLSCAN_API_KEY}", url = "https://scrollscan.com" }
scroll_sepolia = { key = "${SCROLLSCAN_API_KEY}", url = "https://sepolia.scrollscan.com" }
